name: Build Windows Executable

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build EXE with PyInstaller
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'  # Specify your Python version

    - name: Extract branch name and set image tag
      id: vars
      run: |
        # Using PowerShell for string manipulation on Windows
        $branchName = $env:GITHUB_REF -replace 'refs/tags/', ''
        $imageTag = $branchName -replace '/', '-'
        echo "BRANCH_NAME=$branchName" >> $env:GITHUB_ENV
        echo "IMAGE_TAG=$imageTag" >> $env:GITHUB_ENV
        echo "GITHUB_REF=$env:GITHUB_REF"
        echo "IMAGE_TAG=$imageTag"
        echo $imageTag > image_tag.txt
      shell: pwsh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed borderx.py

    - name: Upload the executable as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: borderx-$(cat image_tag.txt)
        path: dist/*.exe
