name: Build Windows Executable

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build EXE with PyInstaller
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'  # Specify your Python version

    - name: Extract branch name and set image tag
      id: vars
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/tags/}
        IMAGE_TAG=$(echo $BRANCH_NAME | tr '/' '-')
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "GITHUB_REF=$GITHUB_REF"
        echo "IMAGE_TAG=$IMAGE_TAG"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed borderx.py

    - name: Upload the executable as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: borderx-${{ env.IMAGE_TAG }}
        path: dist/*.exe
